services:
  manus-postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=manus
    volumes:
      - manus_postgres_data:/var/lib/postgresql

  manus-redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - manus_redis_data:/data

  manus-vector-store:
    image: pgvector/pgvector:pg16
    hostname: 127.0.0.1
    ports: 
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=manus
    volumes:
      - manus_vector_store_data:/var/lib/postgresql


volumes:
  manus_postgres_data:
  manus_redis_data:
  manus_vector_store_data: